# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/mc8051_rom/mc8051_rom/mc8051_rom.xci
# IP: The module: 'mc8051_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/mc8051_rom/mc8051_rom/mc8051_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mc8051_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/mc8051_rom/mc8051_rom/mc8051_rom.xci
# IP: The module: 'mc8051_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/mc8051_rom/mc8051_rom/mc8051_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mc8051_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
