# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/prescaler/prescaler/prescaler.xci
# IP: The module: 'prescaler' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/prescaler/prescaler/prescaler_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'prescaler'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/prescaler/prescaler/prescaler.xdc
# XDC: The top module name and the constraint reference have the same name: 'prescaler'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/prescaler/prescaler/prescaler_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prescaler'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/prescaler/prescaler/prescaler.xci
# IP: The module: 'prescaler' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/prescaler/prescaler/prescaler_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'prescaler'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/prescaler/prescaler/prescaler.xdc
# XDC: The top module name and the constraint reference have the same name: 'prescaler'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/prescaler/prescaler/prescaler_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prescaler'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
