# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/prescaler/prescaler/prescaler.xci
# IP: The module: 'prescaler' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/prescaler/prescaler/prescaler_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'prescaler'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/prescaler/prescaler/prescaler.xdc
# XDC: The top module name and the constraint reference have the same name: 'prescaler'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/prescaler/prescaler/prescaler_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prescaler'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: d:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/prescaler/prescaler/prescaler.xci
# IP: The module: 'prescaler' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/prescaler/prescaler/prescaler_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'prescaler'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/prescaler/prescaler/prescaler.xdc
# XDC: The top module name and the constraint reference have the same name: 'prescaler'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/prescaler/prescaler/prescaler_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prescaler'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
