# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/mc8051_ram/mc8051_ram/mc8051_ram.xci
# IP: The module: 'mc8051_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/mc8051_ram/mc8051_ram/mc8051_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mc8051_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/mc8051_ram/mc8051_ram/mc8051_ram.xci
# IP: The module: 'mc8051_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/mc8051_ram/mc8051_ram/mc8051_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mc8051_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
