# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/mc8051_ram/managed_ip_project/managed_ip_project.cache/wt [current_project]
set_property parent.project_path D:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/mc8051_ram/managed_ip_project/managed_ip_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_ip -quiet d:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/mc8051_ram/mc8051_ram/mc8051_ram.xci
set_property is_locked true [get_files d:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/mc8051_ram/mc8051_ram/mc8051_ram.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top mc8051_ram -part xc7a35tcpg236-1 -mode out_of_context

rename_ref -prefix_all mc8051_ram_

write_checkpoint -force -noxdef mc8051_ram.dcp

catch { report_utilization -file mc8051_ram_utilization_synth.rpt -pb mc8051_ram_utilization_synth.pb }

if { [catch {
  file copy -force D:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/mc8051_ram/managed_ip_project/managed_ip_project.runs/mc8051_ram_synth_1/mc8051_ram.dcp d:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/mc8051_ram/mc8051_ram/mc8051_ram.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub d:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/mc8051_ram/mc8051_ram/mc8051_ram_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub d:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/mc8051_ram/mc8051_ram/mc8051_ram_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim d:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/mc8051_ram/mc8051_ram/mc8051_ram_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim d:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/mc8051_ram/mc8051_ram/mc8051_ram_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir D:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/mc8051_ram/ip_user_files/ip/mc8051_ram]} {
  catch { 
    file copy -force d:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/mc8051_ram/mc8051_ram/mc8051_ram_stub.v D:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/mc8051_ram/ip_user_files/ip/mc8051_ram
  }
}

if {[file isdir D:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/mc8051_ram/ip_user_files/ip/mc8051_ram]} {
  catch { 
    file copy -force d:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/mc8051_ram/mc8051_ram/mc8051_ram_stub.vhdl D:/work/mc8051_basys3/hw/generate/artix7_xc7a35tcpg263_1/mc8051_ram/ip_user_files/ip/mc8051_ram
  }
}
