# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/impl/VGA-Controler.cache/wt [current_project]
set_property parent.project_path C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/impl/VGA-Controler.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
add_files C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/src/Testbild_320x240.coe
add_files C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/src/Finger_100x100.coe
add_files -quiet c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/MU1/MU1/MU1.dcp
set_property used_in_implementation false [get_files c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/MU1/MU1/MU1.dcp]
add_files -quiet c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/MU2/MU2/MU2.dcp
set_property used_in_implementation false [get_files c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/MU2/MU2/MU2.dcp]
read_vhdl -library xil_defaultlib {
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/vga_ctrl_.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/content_ctrl_.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/io_ctrl_.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/vga_ctrl_rtl.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/top_.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/content_ctrl_rtl.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/io_ctrl_rtl.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/top_struc.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/impl/VGA-Controler.srcs/constrs_1/new/VGA-Contrler-constrs.xdc
set_property used_in_implementation false [get_files C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/impl/VGA-Controler.srcs/constrs_1/new/VGA-Contrler-constrs.xdc]


synth_design -top vga_controler_top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef vga_controler_top.dcp

catch { report_utilization -file vga_controler_top_utilization_synth.rpt -pb vga_controler_top_utilization_synth.pb }
