# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/impl/VGA-Controler.cache/wt [current_project]
set_property parent.project_path C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/impl/VGA-Controler.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
add_files C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/src/Testbild_320x240.coe
add_files C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/src/Finger_100x100.coe
add_files C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/sw/build/mc8051_rom.coe
add_files -quiet c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/MU3/MU3/MU3.dcp
set_property used_in_implementation false [get_files c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/MU3/MU3/MU3.dcp]
add_files -quiet c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/MU2/MU2/MU2.dcp
set_property used_in_implementation false [get_files c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/MU2/MU2/MU2.dcp]
add_files -quiet c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/MU1/MU1/MU1.dcp
set_property used_in_implementation false [get_files c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/MU1/MU1/MU1.dcp]
add_files -quiet c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/mc8051_ram/mc8051_ram/mc8051_ram.dcp
set_property used_in_implementation false [get_files c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/mc8051_ram/mc8051_ram/mc8051_ram.dcp]
add_files -quiet c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/PLL/PLL/PLL.dcp
set_property used_in_implementation false [get_files c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/PLL/PLL/PLL.dcp]
add_files -quiet c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/mc8051_rom/mc8051_rom/mc8051_rom.dcp
set_property used_in_implementation false [get_files c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/mc8051_rom/mc8051_rom/mc8051_rom.dcp]
read_ip -quiet C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/MU3/MU3/MU3.xci
set_property used_in_implementation false [get_files -all c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/MU3/MU3/MU3_ooc.xdc]
set_property is_locked true [get_files C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/MU3/MU3/MU3.xci]

read_ip -quiet C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/MU2/MU2/MU2.xci
set_property used_in_implementation false [get_files -all c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/MU2/MU2/MU2_ooc.xdc]
set_property is_locked true [get_files C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/MU2/MU2/MU2.xci]

read_ip -quiet C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/MU1/MU1/MU1.xci
set_property used_in_implementation false [get_files -all c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/MU1/MU1/MU1_ooc.xdc]
set_property is_locked true [get_files C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/MU1/MU1/MU1.xci]

read_ip -quiet C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/mc8051_ram/mc8051_ram/mc8051_ram.xci
set_property used_in_implementation false [get_files -all c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/mc8051_ram/mc8051_ram/mc8051_ram_ooc.xdc]
set_property is_locked true [get_files C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/mc8051_ram/mc8051_ram/mc8051_ram.xci]

read_ip -quiet C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/PLL/PLL/PLL.xci
set_property used_in_implementation false [get_files -all c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/PLL/PLL/PLL_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/PLL/PLL/PLL.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/PLL/PLL/PLL_ooc.xdc]
set_property is_locked true [get_files C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/PLL/PLL/PLL.xci]

read_vhdl -library xil_defaultlib {
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/addsub_ovcy_.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/addsub_cy_.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/mc8051_p.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/dcml_adjust_.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/control_mem_.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/control_fsm_.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/comb_mltplr_.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/comb_divider_.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/alumux_.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/alucore_.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/addsub_ovcy_rtl.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/addsub_cy_rtl.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/addsub_core_.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/mc8051_tmrctr_.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/mc8051_siu_.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/mc8051_control_.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/mc8051_alu_.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/dcml_adjust_rtl.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/control_mem_rtl.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/control_fsm_rtl.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/comb_mltplr_rtl.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/comb_divider_rtl.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/alumux_rtl.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/alucore_rtl.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/addsub_core_struc.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/mc8051_tmrctr_rtl.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/mc8051_siu_rtl.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/mc8051_core_.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/mc8051_control_struc.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/mc8051_alu_struc.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/content_ctrl_.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/content_ctrl_rtl_mem2.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/mc8051_top_.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/mc8051_core_struc.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/vga_ctrl_.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/io_ctrl_.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/content_ctrl_rtl_mem1.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/mc8051/mc8051_top_struc.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/vga_ctrl_rtl.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/top_.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/io_ctrl_rtl.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/content_ctrl_rtl_config.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/top_struc_mem2.vhd
  C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/vhdl/top_struc_config.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/impl/VGA-Controler.srcs/constrs_1/new/VGA-Contrler-constrs.xdc
set_property used_in_implementation false [get_files C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/impl/VGA-Controler.srcs/constrs_1/new/VGA-Contrler-constrs.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top vga_controler_top_cfg -part xc7a35tcpg236-1


write_checkpoint -force -noxdef vga_controler_top_cfg.dcp

catch { report_utilization -file vga_controler_top_cfg_utilization_synth.rpt -pb vga_controler_top_cfg_utilization_synth.pb }
