# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/MU3/MU3/MU3.xci
# IP: The module: 'MU3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/MU3/MU3/MU3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MU3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/MU3/MU3/MU3.xci
# IP: The module: 'MU3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/MU3/MU3/MU3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MU3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
