# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/VGA-Contrler-constrs.xdc

# IP: C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/MU2/MU2/MU2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MU2 || ORIG_REF_NAME==MU2}]

# IP: C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/MU1/MU1/MU1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MU1 || ORIG_REF_NAME==MU1}]

# IP: C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/mc8051_ram/mc8051_ram/mc8051_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mc8051_ram || ORIG_REF_NAME==mc8051_ram}]

# IP: C:/Users/Paul/Desktop/Technikum/4_Semester/CHD/VGA-Controler/generate/PLL/PLL/PLL.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PLL || ORIG_REF_NAME==PLL}]
